### PR TITLE
Add a CMake workflow for building a CLAP from a pre-built Projucer project

### PR DESCRIPTION
**Pull request by jatinchowdhury18**
So far I've been testing this process with an [example plugin](https://github.com/jatinchowdhury18/plugin-ci-example), and with local builds of @reales's [OB-Xd](https://github.com/reales/OB-Xd).

I've written up some instructions for the process in a separate Markdown file, but we could move it to the README if you prefer.

### CODE REVIEW

**Comment by baconpaul** [comment]
This is both fantastic and clever.

I would prefer to have this in the main README and adjust the README to make it seem like we can work with CMake and Projucer both! Do you mind?

**Comment by jatinchowdhury18** [comment]
Sure thing! I'll work on merging that text into the README, while trying to keep everything organized.

I'm also thinking of trying to refactor some of the CMake scripts so that there's less repetition... so if we change something (e.g. how we're handling `CXX_STANDARD`), the change will propagate to both build workflows as needed.

**Comment by baconpaul** [comment]
Excellent. 

Happy for you to merge this but just one tiny change before you do. The title of the README (the one with "# " at the very first line) still says "JUCE 6/7 CMAKE" and we can remove the CMAKe there

Also just checking - did you test (say) surge and one other (dexed? odin2? b-step?) build with this change?

If so super happy for you to merge! And this is awesome!!

**Comment by jatinchowdhury18** [comment]
Sure thing! At the moment I've tested this branch with OB-Xd, BYOD, Surge, B-Step, and my little tester plugin.

**Comment by baconpaul** [comment]
awesome!

**Pull request merged**
