### PR TITLE
Improve the generated MacOSX bundle

### LINKED ISSUE #17: clap Does not appear as a bundle in finder on macOS
Right now it is missing so we just look like a folder etc...

### PR DESCRIPTION
**Pull request by baconpaul**
1. Have a info.plist template so we can control it
2. make it a BNDL
3. Add a PkgInfo so it appears as a folder (closes #17)
4. Attempt to make an icon work, but it doesn't, but leave
   that code here anyway

### CODE REVIEW

**Comment by baconpaul** [comment]
OK darn it i'm out of time before my vacation. I will leave this here since it works cmake side and if @jatinchowdhury18 you get a chance in next two weeks, feel free to merge, otherwise I will fix when I return!

Sorry

**Comment by jatinchowdhury18** [comment]
No worries! i have a decent idea how to fix it from the Projucer side, so I can look at it from there.

**Review by jatinchowdhury18 — APPROVED** [review]
I ended up making a few more tweaks than I anticipated, so I won't merge until Paul takes another glance at it.

**Comment by baconpaul** [comment]
Oh ha yes that is a far more correct version to use! Thank you! Looks great to me

**Pull request merged**
