### PR TITLE
Projucer: Try linking with JUCE helper targets

### PR DESCRIPTION
**Pull request by jatinchowdhury18**
Just going to hold off on merging this until a couple folks test out these changes.

### CODE REVIEW

**Comment by jatinchowdhury18** [comment]
@baconpaul just wanted to check with you before merging this.

**Comment by baconpaul** [comment]
@jatinchowdhury18 incant beleive I missed this! I just saw it hanging out here. It still looks good but I bet it needs rebasing :) shall we do that or close it?

**Comment by jatinchowdhury18** [comment]
Ah, I had also forgotten about it! I'm having a hard time remembering the motivations behind some of these changes, but I think a couple of them are definitely still worth doing.

**Comment by jatinchowdhury18** [comment]
Okay, I've been through it again, and I think these changes should be fine to add as-is. @baconpaul do you think this is okay to merge?

**Comment by baconpaul** [comment]
Yes! I’ll merge it now

**Pull request merged**
