### PR TITLE
Implementing param-indication extension

### PR DESCRIPTION
**Pull request by jatinchowdhury18**

### CODE REVIEW

**Comment by baconpaul** [comment]
Wow this has been sitting here forever - sorry @jatinchowdhury18 

once i merge the 1.2.0 change this morning lets rebase this. Still something we want yeah?

**Comment by jatinchowdhury18** [comment]
Ah, I had forgotten about it also... I'm not sure that I'm going to implement this in my plugins, but it would definitely be good to have support for it in the wrapper generally!

**Comment by jatinchowdhury18** [comment]
Finally got around to rebasing this PR. @baconpaul if you have a minute to glance at this that would be great!

**Comment by baconpaul** [comment]
Looks great! Merging now.

**Pull request merged**
